### ISSUE TITLE
Modifications 

### ISSUE THREAD

**Issue by phelipe** [lepisma/Fuzzy.jl#3]
I did some modifications on code and created others types, probably I will do the code support mimo systems beyond miso systems. Do you think we need to create a organization for the repository? Like Julia Fuzzy?!

**Comment by lepisma** [comment]
Thanks for working on this!
Though I don't think I will be able to participate in / maintain the project.
I will link your [repo](https://github.com/phelipe/Fuzzy.jl) in mine as the *active one*.

**Edit:** Unmaintained repo note 70fe7df9ef58f76635e953b86be729b6f3924a1d

**Comment by phelipe** [comment]
ok! Thank you, your package was very helpful for me.
